---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: zk-solr1
    box: centos/7
    hostname: zk-solr1
    memory: 2048
    cpus: 1
    interfaces:
      - network_name: private_network
        ip: 10.0.1.111
      - network_name: forwarded_port
        guest: 8080
        host: 8888
      - network_name: forwarded_port
        guest: 8983
        host: 8983
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"

  - name: zk-solr2
    box: centos/7
    hostname: zk-solr2
    memory: 2048
    cpus: 1
    interfaces:
      - network_name: private_network
        ip: 10.0.1.112
      - network_name: forwarded_port
        guest: 8080
        host: 8888
      - network_name: forwarded_port
        guest: 8983
        host: 8984
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"

  - name: zk-solr3
    box: centos/7
    hostname: zk-solr3
    memory: 2048
    cpus: 1
    interfaces:
      - network_name: private_network
        ip: 10.0.1.113
      - network_name: forwarded_port
        guest: 8080
        host: 8888
      - network_name: forwarded_port
        guest: 8983
        host: 8985
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"

provisioner:
  name: ansible
verifier:
  name: testinfra
